### ISSUE TITLE
Facebook SDK v7.16.0 NullReferenceExceptions on iOS

### ISSUE THREAD

**Issue by renattou** [facebook/facebook-sdk-for-unity#252] opened 2019-06-07 23:50 UTC
After installing v7.16.0, the SDK throws an error almost every time I interact with it (for example when calling `FB.LogInWithReadPermissions`).

The error is as follows:
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Facebook.Unity.CodelessUIInteractEvent.Update () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Facebook.Unity.CodelessUIInteractEvent:Update()

(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
```

I'm using Unity 2018.4.0f1, Xcode 10.1, iOS 12.3.1 and .NET 4.x.

**Comment by EmpTim** [comment] 2019-06-10 00:27
I found this was happening when I upgraded to 7.16.0 from 7.15.1. I discovered that the issue seemed to related to the fact by upgrading and not doing a clean install of the SDK, some previous files were left over causing all sorts of conflicts. I suggest deleting the FacebookSDK folder and the PlayServicesResolver, and then reinstalling 7.16.0.

**Comment by myrik** [comment] 2019-06-10 18:47
I'm having the same NullReferenceException on Android 9 using Unity 2018.3.10f1. I did try completely deleting the FacebookSDK folder before importing version 7.16.0

**Comment by renattou** [comment] 2019-06-10 19:28
@EmpTim I already tried on a clean project and I still had this problem :/

**Comment by kodekq** [comment] 2019-06-11 09:29
I have the same issue.

**Comment by num0n1** [comment] 2019-06-14 09:03
same here, i did do a clean upgrade and still, on Unity 2018.3.1f1, target for android

`System.NullReferenceException: Object reference not set to an instance of an object
  at Facebook.Unity.CodelessUIInteractEvent.Update () [0x00096] in <9e96dd869f63450fb1f0ac2350bd157e>:0 
UnityEngine.Debug:Log(Object)
Facebook.Unity.CodelessUIInteractEvent:Update()
`

**Comment by mjokipii** [comment] 2019-06-17 21:19
We have this too. Clean install. It seems not to be an unhandled exception but simply a log message from Facebook SDK internals. Does anyone know whether v7.16.0 still functions or not?

**Comment by Olszewskim** [comment] 2019-06-18 13:17
We have clean install of v7.16.0 too. The same issue. This error occurs in Editor, Android, and iOS.

**Comment by daCelky** [comment] 2019-06-18 14:51
Same issue here, Does it have any consequence on analytics logs ? I have to wait 24 hours before seeing any log to know if it has any impact.

**Comment by alex-turantsev** [comment] 2019-06-18 19:52
Same issue. please solve this problem

**Comment by Albob** [comment] 2019-06-20 11:49
Same here. I can see it in the editor, haven't tried iOS or Android.
I did a semi-clean install: removed all FB files, but kept the PlayServicesResolver files.

**Comment by KylinChang** [comment] 2019-06-23 19:16
The issue is fixed in v7.16.1

**Closed by KylinChang** 2019-06-23 19:16 UTC

**Comment by VoxelMatt** [comment] 2019-07-05 02:33
I'm getting this issue in FB 7.17.0.
I've noticed that the Facebook SDK creates an EventSystem if one is not found, but my app manages it's own event systems. And if I delete the one that FB creates, then I get this error.
Can you just make the code try to find an existing event system if the one it has is deleted?

Thanks :)

**Comment by kodekq** [comment] 2019-07-18 15:58
Still have this issue in 7.17.1

**Comment by ernesernesto** [comment] 2019-08-21 06:57
Same issue as VoxelMatt and kodekq, I'm also using fb unity 7.17.1 with error log

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Facebook.Unity.CodelessUIInteractEvent.Update () [0x00000] in <00000000000000000000000000000000>:0 
Facebook.Unity.CodelessUIInteractEvent:Update()
```

**Comment by kreso22** [comment] 2019-08-23 21:26
Same issue in 17.7.2

`System.NullReferenceException: Object reference not set to an instance of an object
  at Facebook.Unity.CodelessUIInteractEvent.Update () [0x0002c] in <f291c17795434dc28c3b2c582bb2d4c3>:0`
