### ISSUE TITLE
v7.17.0 Login Crash iOS

### ISSUE THREAD

**Issue by kdzapp** [facebook/facebook-sdk-for-unity#267] opened 2019-06-28 20:35 UTC
```
2019-06-28 13:33:39.364636-0700 quests[3086:590813] -[__NSCFNumber length]: unrecognized selector sent to instance 0xa4983d641edb4b5d
2019-06-28 13:33:39.406008-0700 quests[3086:590813] Uncaught exception: NSInvalidArgumentException: -[__NSCFNumber length]: unrecognized selector sent to instance 0xa4983d641edb4b5d
(
	0   CoreFoundation                      0x0000000187e11294 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000186feb9f8 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000187d2dab8 <redacted> + 0
	3   CoreFoundation                      0x0000000187e16ac4 <redacted> + 1408
	4   CoreFoundation                      0x0000000187e1875c _CF_forwarding_prep_0 + 92
	5   quests                              0x00000001010be028 +[FBSDKRestrictiveDataFilterManager isMatchedWithPattern:text:] + 128
	6   quests                              0x00000001010bde90 +[FBSDKRestrictiveDataFilterManager getMatchedDataTypeWithEventName:paramKey:paramValue:] + 892
	7   quests                              0x0000000101085330 -[FBSDKAppEvents instanceLogEvent:valueToSum:parameters:isImplicitlyLogged:accessToken:] + 752
	8   quests                              0x0000000101084538 +[FBSDKAppEvents logInternalEvent:valueToSum:parameters:isImplicitlyLogged:accessToken:] + 172
	9   quests                              0x0000000101084340 +[FBSDKAppEvents logInternalEvent:parameters:isImplicitlyLogged:] + 76
	10  quests                              0x00000001010dc328 -[FBSDKLoginManagerLogger logEvent:params:] + 200
	11  quests                              0x00000001010db470 -[FBSDKLoginManagerLogger startSessionForLoginManager:] + 724
	12  quests                              0x00000001010d9b30 -[FBSDKLoginManager logInWithPermissions:handler:] + 304
	13  quests                              0x00000001010d8714 -[FBSDKLoginManager logInWithPermissions:fromViewController:handler:] + 168
	14  quests                              0x0000000101071904 -[FBUnityInterface startLogin:scope:isPublishPermLogin:] + 248
	15  quests                              0x0000000101072994 IOSFBLogInWithReadPermissions + 76
	16  quests                              0x0000000101eadc84 IOSWrapper_LogInWithReadPermissions_mFAAD75436D210A2F2B0E03BDA785DB1282209EF1 + 40
	17  quests                              0x00000001025fd194 UnityAction_Invoke_mC9FF5AA1F82FDE635B3B6644CE71C94C31C3E71A + 492
	18  quests                              0x0000000102605278 UnityEvent_Invoke_mB2FA1C76256FE34D5E7F84ABE528AC61CE8A0325 + 380
	19  quests                              0x000000010222b1b8 EventFunction_1_Invoke_m7B4AC95E7BAF5767E88C6D1DAFEFEA8E3B8F7E5B_gshared + 904
	20  quests                              0x0000000101f268d0 ExecuteEvents_Execute_TisRuntimeObject_mF60803A6735863DACF0DFEAD76FB57B7F307C612_gshared + 380
	21  quests                              0x00000001026667cc StandaloneInputModule_ProcessTouchPress_m6D785DFE91DB756A2D9337FE2F1CB26C1EAA38C0 + 968
	22  quests                              0x0000000102665f08 StandaloneInputModule_ProcessTouchEvents_mBED4842DB8EB55D163C92FC142466D0DF9E28B5F + 208
	23  quests                              0x0000000102665c98 StandaloneInputModule_Process_mDFF8B9EF1AF451E850E161B5C0BEE5A021DB0DC9 + 84
	24  quests                              0x0000000100ffb00c _Z65RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017PFvvEPK10MethodInfoPvPS4_ + 20
	25  quests                              0x0000000101d61674 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
	26  quests                              0x000000010179a4b8 _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
	27  quests                              0x00000001017a3788 _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 116
	28  quests                              0x00000001017a91c0 _ZN13MonoBehaviour16CallUpdateMethodEi + 300
	29  quests                              0x000000010163421c _ZN20BaseBehaviourManager12CommonUpdateI16BehaviourManagerEEvv + 224
	30  quests                              0x00000001016f3948 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 88
	31  quests                              0x00000001016f397c _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 140
	32  quests                              0x00000001016f3b64 _Z10PlayerLoopv + 236
	33  quests                              0x0000000101964df8 _ZL19UnityPlayerLoopImplb + 52
	34  quests                              0x0000000100f6df8c UnityRepaint + 140
	35  quests                              0x0000000100f6de78 -[UnityAppController(Rendering) repaintDisplayLink] + 88
	36  GPUToolsCore                        0x0000000107a689fc -[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 200
	37  QuartzCore                          0x000000018c198f90 <redacted> + 636
	38  QuartzCore                          0x000000018c262b10 <redacted> + 272
	39  CoreFoundation                      0x0000000187d7ca8c <redacted> + 188
	40  CoreFoundation                      0x0000000187da3690 <redacted> + 56
	41  CoreFoundation                      0x0000000187da2ddc <redacted> + 440
	42  CoreFoundation                      0x0000000187d9dc00 <redacted> + 2096
	43  CoreFoundation                      0x0000000187d9d0b0 CFRunLoopRunSpecific + 436
	44  GraphicsServices                    0x0000000189f9d79c GSEventRunModal + 104
	45  UIKitCore                           0x00000001b4609978 UIApplicationMain + 212
	46  quests                              0x0000000100f66cb0 main + 160
	47  libdyld.dylib                       0x00000001878628e0 <redacted> + 4
```

Facebook login is crashing with the latest update (wasn't happening in 7.16.0) any ideas?

**Comment by sergiymomot** [comment] 2019-06-28 20:42
Have the same issue with native iOS app in prod

**Comment by IneOtherGuys** [comment] 2019-06-28 20:46
Same issue in version 7.16.1, LogInWithReadPermissions triggers the exact same crash.

**Comment by OniTheC4t** [comment] 2019-06-29 09:54
Same issue here

**Comment by KylinChang** [comment] 2019-07-01 06:45
The issue is not related to login and it should be fixed now.

**Closed by KylinChang** 2019-07-01 06:45 UTC

**Comment by OniTheC4t** [comment] 2019-07-01 08:28
What do you mean for "now"?
In the next sdk release?

**Comment by KylinChang** [comment] 2019-07-01 22:03
Hey @OniTheC4t, the issue should also be fixed in the current version. You don't have wait for the next SDK release.
