### ISSUE TITLE
Crash on iOS Unity 2018.2.18f when press login

### ISSUE THREAD

**Issue by cindyqin2015** [facebook/facebook-sdk-for-unity#205] opened 2018-12-22 02:32 UTC
Unity SDK version is: 7.15.0, I try iOS version 8.0 or 11.4, both same crash:

2018-12-22 10:24:35.105635+0800 facebook[1643:108375] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2018-12-22 10:24:35.115733+0800 facebook[1643:108375] -canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2018-12-22 10:24:35.116354+0800 facebook[1643:108375] +[NSError fbUnknownErrorWithMessage:]: unrecognized selector sent to class 0x1fa6dcf80
2018-12-22 10:24:35.181284+0800 facebook[1643:108375] Uncaught exception: NSInvalidArgumentException: +[NSError fbUnknownErrorWithMessage:]: unrecognized selector sent to class 0x1fa6dcf80
(
	0   CoreFoundation                      0x00000001c094feb8 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001bfb21a40 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001c086ddac <redacted> + 0
	3   CoreFoundation                      0x00000001c09557b8 <redacted> + 1412
	4   CoreFoundation                      0x00000001c095745c _CF_forwarding_prep_0 + 92
	5   facebook                            0x00000001046476a0 +[FBSDKInternalUtility URLWithScheme:host:path:queryParameters:error:] + 584
	6   facebook                            0x00000001046465a4 +[FBSDKInternalUtility

**Comment by fokazaki2** [comment] 2018-12-24 12:18
I have the same problem.

**Comment by creatio-ua** [comment] 2018-12-27 18:32
Having the same problem.

**Comment by promrithy** [comment] 2018-12-29 10:39
Having the same problem and downgrade Facebook SDK to 7.14.1 solved.

**Comment by KylinChang** [comment] 2019-01-11 00:51
Hey @cindyqin2015 @fokazaki2  @creatio-ua  @promrithy , the issue is fixed in FB Unity SDK v7.15.1.

**Comment by promrithy** [comment] 2019-01-11 03:30
Thank you @KylinChang I will test it later.

**Closed** 2019-01-14 21:53 UTC
