### ISSUE TITLE
Issues with Android IL2CPP Compilation

### ISSUE THREAD

**Issue by InfiniteCode** [facebook/facebook-sdk-for-unity#32] opened 2016-08-19 19:59 UTC
The current version of Facebook SDK for Unity (7.8.0) doesn't work well with Android IL2CPP compilation. Fails with the following:

```
[10:39:56][Step 2/5] Failed running /Users/user/Library/Android/ndk//toolchains/llvm-3.6/prebuilt/darwin-x86_64/bin/clang++ -o "Temp/StagingArea/assets/bin/Data/Native/x86/libil2cpp.so.debug" -Wl,-soname,libil2cpp.so.debug --sysroot "/Users/user/Library/Android/ndk/platforms/android-9/arch-x86" -gcc-toolchain "/Users/user/Library/Android/ndk//toolchains/x86-4.9/prebuilt/darwin-x86_64" -target i686-none-linux-android -shared -fuse-ld=gold -Wl,--no-undefined -Wl,-z,noexecstack -Wl,--gc-sections -Wl,--build-id "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Assembly-CSharp-firstpass_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Assembly-CSharp-firstpass_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Assembly-CSharp_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Assembly-CSharp_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Assembly-CSharp_2.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Assembly-CSharp_3.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Facebook.Unity_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_10.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_11.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_12.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_13.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_2.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_3.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_4.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_5.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_6.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_7.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_8.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Generics_9.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Mono.Security_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Mono.Security_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Newtonsoft.Json_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_Newtonsoft.Json_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_SmartLocalization_Runtime_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System.Core_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System.Runtime.Serialization_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System.Xml_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System.Xml_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System.Xml_2.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System.Xml_3.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_System_2.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_UnityEngine.UI_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_UnityEngine.UI_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_UnityEngine_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_UnityEngine_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_UnityEngine_2.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_UnityEngine_3.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_2.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_3.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_4.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_5.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_6.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Bulk_mscorlib_7.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/GenericMethods0.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/GenericMethods1.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppAttributes.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppCodeRegistration.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppCompilerCalculateTypeValuesTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppDelegateWrappersManagedToNativeTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppGenericClassTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppGenericInstDefinitions.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppGenericMethodDefinitions.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppGenericMethodPointerTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppGenericMethodTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppGuids.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppInvokerTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppMarshalingFunctionsTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppMetadataRegistration.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppMetadataUsage.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppMethodPointerTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppReversePInvokeWrapperTable.o" "Temp/StagingArea/Il2Cpp/il2cppOutput/x86/Il2CppTypeDefinitions.o"    -L "/Applications/Unity/PlaybackEngines/AndroidPlayer/Variations/il2cpp/Release/StaticLibs/x86" -lil2cpp -lbdwgc -L "/Users/user/Library/Android/ndk//sources/cxx-stl/gnu-libstdc++/4.9/libs/x86" -lgnustl_static
[10:39:56][Step 2/5] 
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16129: error: undefined reference to 'IOSInit'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16154: error: undefined reference to 'IOSLogInWithReadPermissions'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16154: error: undefined reference to 'IOSLogInWithReadPermissions'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16171: error: undefined reference to 'IOSLogInWithPublishPermissions'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16171: error: undefined reference to 'IOSLogInWithPublishPermissions'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16184: error: undefined reference to 'IOSLogOut'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16184: error: undefined reference to 'IOSLogOut'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16193: error: undefined reference to 'IOSSetShareDialogMode'
[10:39:56][Step 2/5] Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Facebook.Unity_0.cpp:16193: error: undefined reference to 'IOSSetShareDialogMode'
```

**Comment by InfiniteCode** [comment] 2016-08-19 20:00
The issue seems to be coming from Facebook.Unity.dll:

```
$ grep -r IOSInit .
Binary file ./Plugins/Facebook.Unity.dll matches
Binary file ./Plugins/iOS/Facebook.Unity.IOS.dll matches
./SDK/Editor/iOS/FBUnityInterface.mm:  void IOSInit(const char *_appId, bool _frictionlessRequests, const char *_urlSuffix, const char *_userAgentSuffix)
```

**Comment by actislav** [comment] 2016-09-04 09:43
yes ioswrapper with full dll import exists in Facebook.Unity.dll, it must be removed or marked with "#if UNITY_IOS || UNITY_IPHONE"

**Comment by rummanKaiyum** [comment] 2016-09-24 11:28
I can't believe they have not updated it yet! The error is still here with il2cpp. Please fix this error.

**Comment by bosaku** [comment] 2016-09-24 23:19
actislav, can you elaborate? Because we cannot edit the dll, I wonder if you mean we should edit FacebookPostProcess.cs ?

**Comment by bblpny** [comment] 2016-09-27 19:08
bosaku, the problem is that when you build for NDK with IL2CPP facebook dlls contain p/invoke to methods which are not linkable to.

Any p/invoke method declaration when compiling to NDK/IL2CPP on android needs to be linkable. So the fix would be either you remove all P/Invoke from Facebook.Unity.dll, move them to the ios dll and have the unitypackage specify the ios dll is not for android or include some sort of stub .so for android so they are linkable.

**Comment by bblpny** [comment] 2016-09-28 16:43
I attempted to make a .so containing stubbed c functions and it does not work, likely because the p invoke functions use "__Internal" as the module name.
Build failure is here: http://pastebin.com/Wfxc5CAJ

bosaku i think the easiest approach to solve this problem is to first ensure that there are no p/invoke calls in Facebook.Unity.dll, then get rid of Facebook.Unity.IOS.dll entirely in preference to moving the single class in the dll to a .cs in a plugins dir that ifdefs out the pinvoke calls. You'd have to look up the class via Assembly-CSharp first pass, but could alternately use initialize on load from the script into the api.  As it is right now, it seems the only way to get it to compile (even if you set Facebook.Unity.IOS.dll as not included on android) is to manipulate the dll to remove the p/invoke (or use a earlier version).

All in all with the current facebook sdk i've been pretty upset. First my iOS builds did not work because the facebook frameworks packaged with unity sdk are incompatible with xcode 7.2 so I had to manually replace the frameworks with ones from january 2016 just to get it to build, and now i cannot get android to work without significant effort. Does facebook even test all the platforms?

**Comment by nhatnd** [comment] 2016-10-06 12:22
@bblpny: Does your pull request resolve this issue ?

**Comment by bblpny** [comment] 2016-10-06 12:24
nhatnd, yes but I haven't tested iOS yet. Facebook doesn't have Facebook.Unity.IOS and Facebook.Unity.Android projects on github for some reason.

**Comment by nhatnd** [comment] 2016-10-06 12:57
@bblpny: But could you please let me know how to modify the Facebook.Unity.dll ? Or could you give me the dll with your modification ?
Thank you very much.

**Comment by nhatnd** [comment] 2016-10-07 04:01
I tried to download the facebook source and apply bblpny's fix then rebuild it. It can be built now. Hope facebook will make the official fix for this soon.

**Comment by bblpny** [comment] 2016-10-14 10:09
@nhatnd , glad you got it working. Josh has just told me that the fix should be in upcoming 5.4.2p2

**Comment by bosaku** [comment] 2016-10-19 19:00
I'm pretty confused by this conversation. 

What would I do with the code snippet on pastebin? I don't see a file to replace with a similiar structure. 

I tried downloading, and compiling your source in git which fixes the IL2CPP errors, but I receive errors when running ./setup.sh -> FATAL: Failed to copy '/Users/StreamfallMobile/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/23.4.0/support-v4-23.4.0.aar' 

Any other guidance?
Thank you!

**Comment by PimDeWitte** [comment] 2016-11-05 21:03
+1 on a fix for this, experiencing the same issue and it will force us to remove Facebook from Android.

**Comment by bblpny** [comment] 2016-11-10 16:32
Just as a follow-up, the 5.4.2p3 patch only fixes the issue after you remove the references to the IOS pinvoke functions.

So,for those that just want to get android to work i've attached the patched dll that excludes the unlinkable ios pinvoke calls that prevent android il2cpp builds from completing.
To admistrators: If i am breaking any rules by posting this dll please remove the attachment.

Please follow the steps below
Ensure the following:
 - You are running the patch release of unity version 5.4.3p (perhaps 5.3.2p will work as well)
 - You are using 7.8.0 facebook sdk for unity.
 - You either have unity closed before preceeding or will not focus to it while doing the following steps.
Make a backup:
 - Copy the file Facebook.Unity.dll located in Assets/FacebookSDK/Plugins to any folder outside (not within) the Assets folder. (Important if you support iOS and Android)
Extract and replace:
 - Extract Facebook.Unity.Patched.Patched.dll from the attached zip file to the same directory inside of Assets that you made a backup of Facebook.Unity.dll
 - Delete only Facebook.Unity.dll, Do not delete Facebook.Unity.dll.meta if it exists!
 - Rename Facebook.Unity.Patched.Patched.dll to Facebook.Unity.dll
Open or focus to unity.
 - Unity will import the dll, but as long as you did not focus to unity between these steps all asset bindings to monobehaviours or scriptable objects within the facebook dll will retain their references.
 - Build the Android IL2CPP project.

Because this requires that you replace the dll, it breaks iOS support. So in order to build for iOS after this, you need to do the following, under the same restrictions of not focusing or having unity open:
 - Delete the Facebook.Unity.dll that you previously renamed from Facebook.Unity.dll
 - Restore the original Facebook.Unity.dll that you backed up previously.
 - Open unity and build.

Notes about the patch: Reflexil and ILSpy were used to do the following:
- Within the internal problematic class Facebook.Unity.IOSWrapper all static pinvoke methods had the following attributes removed so that they were no longer checked:
     Method Impl: IsPreserveSig
     IsPInvokeImpl
 Then saved as Facebook.Unity.Patched.dll
 - Secondly, to the first patched version, each of the void returning methods were given opcodes to just return:
0(offset) ret 
    and the one string returning method IOSFBSdkVersion given following opcode to return null:
0(offset) Idnull
1(offset) ret

then this was saved off to Facebook.Unity.Patched.Patched.dll

[Facebook.Unity.Patched.Patched.zip](https://github.com/facebook/facebook-sdk-for-unity/files/583850/Facebook.Unity.Patched.Patched.zip)

**Closed** 2017-01-04 21:23 UTC
